### ISSUE TITLE
Add a .gitattributes file so GitHub recognises Genie

### ISSUE THREAD

**Issue by astavale** [darkoverlordofdata/shmupwarz-vala#1]
This project is a really nice demo of Genie. Can you add a `.gitattributes` file containing:

```*.gs linguist-language=Genie```

This will hopefully show the main language used is Genie, rather than JavaScript and Gosu at present. See https://github.com/github/linguist#using-gitattributes

**Comment by darkoverlordofdata** [comment]
Done. Thanks for the tip.
